from __future__ import annotations

PROTOCOL_VERSION = "0.1"

E_BAD_MESSAGE = "E_BAD_MESSAGE"
E_UNSUPPORTED_PROTOCOL = "E_UNSUPPORTED_PROTOCOL"
E_NO_ROUTE = "E_NO_ROUTE"
E_REQUIRED_EXTENSION_MISSING = "E_REQUIRED_EXTENSION_MISSING"
E_CONFIRMATION_REQUIRED = "E_CONFIRMATION_REQUIRED"
E_NODE_UNAVAILABLE = "E_NODE_UNAVAILABLE"
E_NODE_TIMEOUT = "E_NODE_TIMEOUT"
E_NODE_ERROR = "E_NODE_ERROR"
E_NODE_UNTRUSTED = "E_NODE_UNTRUSTED"
E_NODE_NOT_REGISTERED = "E_NODE_NOT_REGISTERED"
E_NODE_REG_INVALID = "E_NODE_REG_INVALID"
E_INTERNAL = "E_INTERNAL"

RISK_READ = "read"
RISK_MUTATE = "mutate"
RISK_DESTRUCTIVE = "destructive"
RISK_CLASSES = {RISK_READ, RISK_MUTATE, RISK_DESTRUCTIVE}

MODEL_PROVIDER_OPENROUTER = "openrouter"
MODEL_PROVIDER_OLLAMA = "ollama"
MODEL_PROVIDERS = {MODEL_PROVIDER_OPENROUTER, MODEL_PROVIDER_OLLAMA}
